Document: openwb
Title: Debian openwb Manual
Author: <insert document author here>
Abstract: This manual describes what openwb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openwb/openwb.sgml.gz

Format: postscript
Files: /usr/share/doc/openwb/openwb.ps.gz

Format: text
Files: /usr/share/doc/openwb/openwb.text.gz

Format: HTML
Index: /usr/share/doc/openwb/html/index.html
Files: /usr/share/doc/openwb/html/*.html
