#!/usr/bin/python
import sys
import time
import struct
from pymodbus.client.sync import ModbusSerialClient

serial_port = str(sys.argv[1])
unit_id_1 = int(sys.argv[2])
unit_id_2 = int(sys.argv[3])
unit_id_3 = int(sys.argv[4])

client = ModbusSerialClient(method="rtu", port=serial_port, baudrate=9600, stopbits=1, bytesize=8, timeout=1)

resp = client.read_input_registers(0x00, 2, unit=unit_id_1)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x06, 2, unit=unit_id_1)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0C, 2, unit=unit_id_1)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x1E, 2, unit=unit_id_1)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0156, 2, unit=unit_id_1)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
time.sleep(0.3)
resp = client.read_input_registers(0x00, 2, unit=unit_id_2)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x06, 2, unit=unit_id_2)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0C, 2, unit=unit_id_2)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x1E, 2, unit=unit_id_2)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0156, 2, unit=unit_id_2)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
time.sleep(0.3)
resp = client.read_input_registers(0x00, 2, unit=unit_id_3)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x06, 2, unit=unit_id_3)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0C, 2, unit=unit_id_3)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x1E, 2, unit=unit_id_3)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
resp = client.read_input_registers(0x0156, 2, unit=unit_id_3)
print(struct.unpack('>f', struct.pack('>HH', *resp.registers)))
