name: Python application

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.5"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest paho-mqtt requests-mock
      - name: Flake8 with annotations
        uses: TrueBrain/actions-flake8@v2.1
        with:
          path: packages
      - name: Test with pytest
        run: |
          cd packages && python -m pytest
